### PR TITLE
Add Color Control

### PR DESCRIPTION
**Pull request by MasaTate**
Hello, YANG Chengkai ! I'm Masatoshi Tateno.  
I got interested in the paper you presented.
So I added color control function.

## What I did
I added `Linear Histogram Matching` function to `test.py`.
Given content image and style image, `Linear Histogram Matching` function transform style image's histogram to match the histogram of the content image.  
Add `--color_control` option to apply color control.

## What is remained
I didn't add color control function to `test_video.py` nor `test_interpolate.py`.

## Test
Tested on CPU and GPU.  
Here is one of the example.  

|brad_pitt_style_flower_of_life_alpha1 0|brad_pitt_style_flower_of_life_alpha1 0_colorcontrol|
|---|---|
|Not matched|Matched|

## issue
#1 

## references

- L. A. Gatys, A. S. Ecker, M. Bethge, A. Hertzmann, and E. Shechtman. Controlling perceptual factors in neural style transfer. In CVPR, 2017. [arxiv](https://arxiv.org/abs/1611.07865)
- A. Hertzmann. Algorithms for Rendering in Artistic Styles. PhD thesis, New York University, 2001.

### CODE REVIEW

**Comment by falseu** [comment]
Hi Masatoshi Tateno. Thank you for your interest and implementation. The color control implementation looks great! 
It would be appreciated to add color control to style interpolation and style video. Here are my suggestions.

- Move `Linear Histogram Matching` to `utils.py`
- Import and use `Linear Histogram Matching` on style tensors in `test.py`, `test_interpolate.py`, and `test_video.py`
- Add input argument to toggle color control in `test_interpolate.py` and `test_video.py`
- In `test_interpolate.py` we have one content image and multiple style images. In `test_video.py`, we have multiple content frames and only one style image. I think it is better to perform `Linear Histogram Matching` to every pair of content-style tensor.

Thank you for your great work!

**Comment by MasaTate** [comment]
Thank you for your review and advice !
I did all you mentioned.

- [x] Move Linear Histogram Matching to utils.py
- [x] Import and use Linear Histogram Matching on style tensors in test.py, test_interpolate.py, and test_video.py
- [x] Add input argument to toggle color control in test_interpolate.py and test_video.py
- [x] In test_interpolate.py we have one content image and multiple style images. In test_video.py, we have multiple content frames and only one style image. I think it is better to perform Linear Histogram Matching to every pair of content-style tensor.

## Result
### interpolate
style image : [flower_of_life , asheville] [0.8 , 0.2]  

|brad_pitt_interpolate_ 0 8, 0 2|brad_pitt_interpolate_ 0 8, 0 2 _colorcontrol|
|---|---|
|w/o color matching|w color matching|



### video
Video quality is not good as image quality in spite of the same implementation.
|https://user-images.githubusercontent.com/45582330/165714061-777bc6f0-deab-4c04-a584-130e1e643239.mp4|https://user-images.githubusercontent.com/45582330/165714124-e8d5c897-bfa3-469d-b721-1d344bb13016.mp4|
|---|---|
|w/o color matching|w color matching|

**Comment by falseu** [comment]
Your implementation is impressive! Color control looks very effective for style transfer and interpolation. In the case of video, each frame follows a different distribution and maybe this is why we have unstable results. Anyways, thank you for your great work and I will merge your pull request.

**Comment by falseu** [comment]
One last thing, could you update README to explain the `--color_control` argument under `usage`, show one color control result under `examples`, and add the reference of color control under `references`? Thank you.

**Pull request merged**
